#!/bin/sh

set -e

case "$1" in
    remove)
        rm -f /etc/modprobe.d/system76-power.conf
        rm -f /etc/modules-load.d/system76-power.conf
        systemctl enable nvidia-fallback.service || true
        ;;

    *)
        ;;
esac

# Automatically added by dh_installsystemd/13.5.1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.5.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'system76-power.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'system76-power.service' >/dev/null || true
		deb-systemd-helper unmask 'system76-power.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
