#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.5.1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'system76-power.service' >/dev/null || true
fi
# End automatically added section
